### ISSUE TITLE
would be nice to provide a test suite

### ISSUE THREAD

**Issue by EricDeveaud** [ndaniel/fastqtk#1]
Hello, 

it would be nice to have a test suite data, command and expected results to test fastqtk

regards

Eric

**Comment by ndaniel** [comment]
Hi @EricDeveaud 

I did some changes and now [test.sh](https://github.com/ndaniel/fastqtk/blob/main/test.sh) can act as test script. Before this `test.sh` was broken (ie. I was using it for debugging).
